### ISSUE TITLE
How to make it work 

### ISSUE THREAD

**Issue by bigpod98** [Sukasa/DistFS#1]
How to make it work i put disk in and go trought wizars and then go to another computer on same network and install but then i cant find files fron other computer

**Comment by Sukasa** [comment]
This is for spanning multiple RAID blocks to appear as a single filesystem mount point.  You want ServerFS, not DistFS.

**Comment by bigpod98** [comment]
I tought this is continuation because serverfs doenst work

**Comment by Sukasa** [comment]
No, this is not related to ServerFS
