### ISSUE TITLE
`touch` fails on nonexistent file with permission error

### ISSUE THREAD

**Issue by NotNite** [Sukasa/DistFS#2]
Hi, sorry for posting an issue on a dead project. I've been trying to get this work for forever and it doesn't seem to work for some reason. I've reinstalled so many times I can't even count.

![The error in question, stating that writing to /distfs failed.](https://tobusc.us/i/j68u.png)

**Comment by NotNite** [comment]
Two things to note:

- this used to work until a few hours ago, making me think it could possibly be a server issue itself
- I just installed it on a brand new machine and am getting the same issue, making me believe so more

**Comment by Sukasa** [comment]
Hoo, been a while since I've looked at this project.  I'll see about taking a look at this to figure out what's going on.

**Comment by Sukasa** [comment]
Turns out the code in the repo was out of date.  I've updated this - haven't had a chance to test it but I'm quite sure this is a working copy from the last time I used this.  I'll see if I can spin up a modpack to test it tomorrow.

**Comment by NotNite** [comment]
Alright, gonna test.

**Comment by Sukasa** [comment]
What version of OpenComputers are you running, and are you using a CPU set for 5.2 or 5.3?

**Comment by NotNite** [comment]
OpenComputers is 1.7.5.192, and I've tried both CPU sets. Also - something VERY weird - it still didn't work.

**Comment by Sukasa** [comment]
Less weird and probably just old code being terrible.  You have my apologies for the trouble; I'll see what I can do to get it fixed!

**Comment by NotNite** [comment]
No problem! Thank you for even working on this anyways - I honestly didn't expect to get a response so fast on a project that hasn't had any interactions since 2017.

**Comment by Sukasa** [comment]
Well I can definitely replicate the bug - cannot `touch` a previously nonexistent file.  Now to figure out _why_

**Comment by NotNite** [comment]
That would make sense, actually - I can write files to individual RAID blocks and they show up in /distfs, but can't do it directly in /distfs.

**Comment by NotNite** [comment]
Apparently `echo "This is a test file!" > test2` works. This seems to be an issue with `touch` alone.

**Comment by Sukasa** [comment]
`io.open("/distfs/notafile", "a")` errors with "notafile does not exist" when it should be creating it.  After digging in, I've found the bug and should have a fix pushed shortly, I hope.

**Comment by Sukasa** [comment]
It doesn't help that `touch` actually does not check the error returned from `io.open()` and substitutes `permission denied` when it should not.

**Comment by Sukasa** [comment]
I've pushed the fix to close this.  As well, editing line 164 of `/lib/distfs.lua` to say `if bRead and not bWrite then` will work as a patch

**Comment by NotNite** [comment]
![Thank you.](https://tobusc.us/i/ngo9.png)
